### ISSUE TITLE
Add a schema version number to the JSON file

### ISSUE THREAD

**Issue by tovrstra** [MolSSI/QCSchema#16]
This is useful when dealing with backward and forward compatibility issues.

**Comment by dgasmith** [comment]
Good point, looks like we have not discussed that yet here. The schema was always meant to be versioned. See some info in #1 about another type of versioning/classification.

**Comment by cryos** [comment]
They key name will help identify the format, and the value will identify the version of the schema. We should use this approach.

**Comment by loriab** [comment]
I'm not following "key name will help identify the format, and the value will identify the version of the schema", @cryos. Do you mean one has to examine the contents of the schema to identify its version/place in the timeline?

I tend to favor an auto-increment with each change to a doc.

**Comment by dgasmith** [comment]
This was done and the final iteration came in #46.
