### ISSUE TITLE
add schema fields to molecule

### ISSUE THREAD

**Issue by loriab** [MolSSI/QCSchema#59]
The molecule schema carries its identifying information ("schema_name" and "schema_version") fields a level higher than the main molecule data. This leads to odd constructions like the below so that one can `to_schema` and `from_schema` directly to the `findif['molecule']` field rather than having to update (`findif.update(mol.to_schema)`) or extract from the big dict.

I agree with minimizing the number of schema versions running around for everyone's sanity. But I wonder if keeping Mol in the main job QCSchema is a consolidation too far. Other experiences?

As alternative, I propose that molecule itself support `{'schema_name': 'qc_mol_schema', 'schema_version': 2}` alongside its data.

```
findif =
{'displacement_space': 'CdSALC',
 'displacements': {'0: -1': {'geometry': [-1.0035217817285502,
                                          -1.5308084989341915e-17,
                                          0.0,
                                          1.0035217817285502,
                                          1.5308084989341915e-17,
                                          0.0]},
                   '0: 1': {'geometry': [-0.9964782182714499,
                                         -1.5308084989341915e-17,
                                         0.0,
                                         0.9964782182714499,
                                         1.5308084989341915e-17,
                                         0.0]}},
 'molecule': {'molecule': {'atom_labels': ['', ''],
                           'atomic_numbers': [1, 1],
                           'fix_com': False,
                           'fix_orientation': False,
                           'fragment_charges': [0.0],
                           'fragment_multiplicities': [1],
                           'fragments': [[0, 1]],
                           'geometry': [-1.0,
                                        -1.5308084989341915e-17,
                                        0.0,
                                        1.0,
                                        1.5308084989341915e-17,
                                        0.0],
                           'mass_numbers': [1, 1],
                           'masses': [1.00782503223, 1.00782503223],
                           'molecular_charge': 0.0,
                           'molecular_multiplicity': 1,
                           'name': 'H2',
                           'provenance': {'creator': 'QCElemental',
                                          'routine': 'qcelemental.molparse.from_string',
                                          'version': 'v0.1.3'},
                           'real': [True, True],
                           'symbols': ['H', 'H']},
              'schema_name': 'qc_schema_input',
              'schema_version': 1},
 'project_rotations': True,
 'project_translations': True,
```

**Comment by dgasmith** [comment]
I think this is pretty reasonable as a Molecule in this context is effectively an object and can be separately versioned.

My only question is should it always require a version and label or can this "cascade" in from a input or output schema?

**Comment by loriab** [comment]
I think the fields have to be present w/i mol. The outer name/version [are required](https://github.com/MolSSI/QCSchema/blob/7669e5e9e85366b6892720041678a37bb1873d60/qcschema/dev/dev_schema.py#L72), so as soon as add to req'd fields for mol, version has to be 2, so cascade won't do any good.

**Comment by dgasmith** [comment]
No, I think you are right. I was thinking from a user perspective that might want to cut some corners when building this out by hand. That however, is an implementation issue and should be handled outside of the schema.
