### ISSUE TITLE
For CCSD(T) add separate entry for (T) contributions to cc_properties

### ISSUE THREAD

**Issue by sjrl** [MolSSI/QCSchema#64]
For CCSD(T) add separate entry for (T) contributions to cc_properties

**Comment by mattwelborn** [comment]
Is this satisfied by https://github.com/MolSSI/QCSchema/blob/54fabe98ae3f31994371e0bfdfc6739dc5a84581/qcschema/dev/properties/cc_properties.py#L47?

**Comment by dgasmith** [comment]
Yes.
